version: '3'
	services:
		postgres_prod:
			image: postgres:latest
			environment:
				POSTGRES_USER: postgres
				POSTGRES_PASSWORD: postgres
				POSTGRES_DB: postgres
			ports:
				- "5432:5432"
		postgres_test:
			image: postgres:latest
			environment:
				POSTGRES_USER: postgres_test
				POSTGRES_PASSWORD: postgres_test
				POSTGRES_DB: postgres_test
			ports:
				- "5433:5432"